# Generated by Django 5.1.7 on 2025-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(choices=[('w3-theme-blue.css', 'blue'), ('w3-theme-light-blue.css', 'light blue'), ('w3-theme-blue-grey.css', 'blue grey'), ('w3-theme-red.css', 'red'), ('w3-theme-black.css', 'black'), ('w3-theme-brown.css', 'brown'), ('w3-theme-cyan.css', 'cyan'), ('w3-theme-grey.css', 'grey'), ('w3-theme-dark-grey.css', 'dark grey'), ('w3-theme-orange.css', 'orange'), ('w3-theme-deep-orange.css', 'deep orange'), ('w3-theme-purple.css', 'purple'), ('w3-theme-deep-purple.css', 'deep purple'), ('w3-theme-green.css', 'green'), ('w3-theme-light-green.css', 'light green'), ('w3-theme-indigo.css', 'indigo'), ('w3-theme-khaki.css', 'khaki'), ('w3-theme-lime.css', 'lime'), ('w3-theme-pink.css', 'pink'), ('w3-theme-teal.css', 'teal'), ('w3-theme-yellow.css', 'yellow')], default='w3-theme-blue.css', max_length=50),
        ),
    ]
