# Generated by Django 5.1.7 on 2025-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lo', 'Lao')], default='la', max_length=2),
        ),
    ]
